services:
  backend:
    image: ${DOCKER_USERNAME}/deces-backend-${EXEC_ENV}:${APP_VERSION}
    container_name: deces-backend-${EXEC_ENV}
    volumes:
      - ${BACKEND_PATH}/src:/${APP}/src/
      - ${BACKEND_PATH}/dist:/${APP}/dist/
      - ${BACKEND_PATH}/tests:/${APP}/tests/
      - ${DATA_DIR}:/${APP}/data/
      - /${APP}/node_modules
    ports:
      - ${PORT}:8080
